import type { MgmtDashboardPayload } from "@/lib/mgmtDashboardTypes"

function localNowLabel(): string {
 const d = new Date()
 const pad = (n: number) => String(n).padStart(2, "0")
 return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`
}

/** Phase 1／無 Supabase 時的同型別假資料，方便 layout 與圖表接線 */
export function buildMgmtDashboardMock(): MgmtDashboardPayload {
 return {
  asOf: localNowLabel(),
  kpis: [
   {
    id: "revenue",
    label: "已收款",
    value: 186500,
    format: "hkd",
    deltaPct: 8.2,
    yoyPct: 12.4,
    targetGap: 6.5,
    targetGapUnit: "percent",
    status: "正常",
    tone: "success",
    sparkline: [142, 158, 151, 170, 172, 186],
   },
   {
    id: "enroll",
    label: "新報讀",
    value: 28,
    format: "count",
    deltaPct: 12.0,
    yoyPct: 5.5,
    targetGap: 3,
    targetGapUnit: "count",
    status: "正常",
    tone: "success",
    sparkline: [18, 22, 20, 25, 24, 28],
   },
   {
    id: "withdraw",
    label: "退讀",
    value: 5,
    format: "count",
    deltaPct: 25.0,
    yoyPct: 10.0,
    targetGap: -2,
    targetGapUnit: "count",
    status: "警示",
    tone: "destructive",
    hint: "目標 ≤ 3",
    sparkline: [2, 3, 2, 4, 3, 5],
   },
   {
    id: "enrolled",
    label: "在讀學生",
    value: 312,
    format: "count",
    deltaPct: 1.6,
    yoyPct: 4.2,
    targetGap: 12,
    targetGapUnit: "count",
    status: "正常",
    tone: "default",
    hint: "全站快照（人數）",
    sparkline: [298, 302, 305, 308, 310, 312],
   },
   {
    id: "enrollmentSeats",
    label: "在讀人次",
    value: 486,
    format: "count",
    deltaPct: 2.4,
    yoyPct: null,
    targetGap: null,
    targetGapUnit: null,
    status: "正常",
    tone: "default",
    hint: "報讀科目加總（1 人報 2 科＝2）",
    sparkline: [450, 458, 465, 472, 480, 486],
   },
   {
    id: "attendanceVisits",
    label: "本月上堂總人次",
    value: 1240,
    format: "count",
    deltaPct: 6.8,
    yoyPct: null,
    targetGap: null,
    targetGapUnit: null,
    status: "正常",
    tone: "success",
    hint: "篩選區間內實際到課人次",
    breakdown: [
     { label: "初中專科班", value: 520 },
     { label: "高中專科班", value: 410 },
     { label: "私人課程", value: 310 },
    ],
    sparkline: [1100, 1140, 1160, 1180, 1210, 1240],
   },
   {
    id: "conversion",
    label: "報讀轉化率",
    value: 60.9,
    format: "percent",
    deltaPct: -4.2,
    yoyPct: 1.8,
    targetGap: -4.1,
    targetGapUnit: "percent",
    status: "注意",
    tone: "warning",
    hint: "試堂→報讀；目標 65%",
    sparkline: [58, 62, 64, 63, 61, 61],
   },
   {
    id: "teacherLoad",
    label: "導師平均負荷",
    value: 34.5,
    format: "count",
    deltaPct: 2.1,
    yoyPct: null,
    targetGap: -4.5,
    targetGapUnit: "count",
    status: "正常",
    tone: "default",
    hint: "平均報讀人次／導師；目標 ≤ 39",
    sparkline: [30, 31, 32, 33, 34, 35],
   },
  ],
  revenueSeries: {
   ok: [
    { label: "2月", amount: 142000, target: 150000 },
    { label: "3月", amount: 158000, target: 155000 },
    { label: "4月", amount: 151200, target: 160000 },
    { label: "5月", amount: 169800, target: 165000 },
    { label: "6月", amount: 172400, target: 170000 },
    { label: "7月", amount: 186500, target: 175000 },
   ],
  },
  funnel: {
   ok: [
    { stage: "試堂", count: 46, conversionPct: null },
    { stage: "新報讀", count: 28, conversionPct: 60.9 },
    { stage: "在讀", count: 312, conversionPct: null },
   ],
  },
  withdrawalAnalysis: {
   ok: {
    bySubject: [
     { label: "英文", count: 2 },
     { label: "數學", count: 2 },
     { label: "中文", count: 1 },
    ],
    byTeacher: [
     { label: "陳老師", count: 2 },
     { label: "李老師", count: 2 },
     { label: "王老師", count: 1 },
    ],
    byClass: [
     { label: "英文 F3A", count: 2 },
     { label: "數學 F4B", count: 2 },
     { label: "中文 F2C", count: 1 },
    ],
    byDate: [
     { label: "07-08", count: 1 },
     { label: "07-12", count: 2 },
     { label: "07-18", count: 1 },
     { label: "07-22", count: 1 },
    ],
   },
  },
  unpaidOverdue: { ok: [
   {
    id: "p1",
    studentName: "陳小明",
    paymentDate: "2026-07-01",
    amount: 2750,
    overdueDays: 23,
    status: "待繳費",
    followUpStatus: "待跟進",
   },
   {
    id: "p2",
    studentName: "李美華",
    paymentDate: "2026-07-05",
    amount: 1650,
    overdueDays: 19,
    status: "待收款",
    followUpStatus: "跟進中",
   },
   {
    id: "p3",
    studentName: "王大文",
    paymentDate: "2026-07-10",
    amount: 825,
    overdueDays: 14,
    status: "待繳費",
    followUpStatus: "已聯繫",
   },
   {
    id: "p4",
    studentName: "張雅婷",
    paymentDate: "2026-07-15",
    amount: 3300,
    overdueDays: 9,
    status: "待繳費",
    followUpStatus: "待跟進",
   },
  ] },
  opsAlerts: [
   {
    id: "a1",
    category: "unpaid",
    severity: "警示",
    title: "欠費學生需立即跟進",
    detail: "有 4 筆逾期待繳費，合計 HK$ 8,525",
    href: "/PaymentHistory",
    count: 4,
   },
   {
    id: "a2",
    category: "withdraw",
    severity: "警示",
    title: "近 7 日退讀偏高",
    detail: "近 7 日退讀 5 人，英文／數學各 2 人",
    count: 5,
   },
   {
    id: "a3",
    category: "lowAttendance",
    severity: "注意",
    title: "低出席班別",
    detail: "英文 F3A、理科 F4 近兩週出席率低於 70%（示範資料）",
    count: 2,
   },
   {
    id: "a4",
    category: "nearFull",
    severity: "注意",
    title: "滿班／接近滿班",
    detail: "數學 F4B 已滿；英文 F3A 滿班率 90%",
    href: "/Classes",
    count: 2,
   },
   {
    id: "a5",
    category: "teacherLoad",
    severity: "注意",
    title: "導師負荷過高",
    detail: "陳老師報讀人次 42，高於建議上限 39",
    count: 1,
   },
   {
    id: "a6",
    category: "conversionDrop",
    severity: "注意",
    title: "轉化率異常下降",
    detail: "整體試堂→報讀轉化率環比下降 4.2 個百分點",
    count: 1,
   },
  ],
  opsAlertsError: null,
  distribution: {
   bySubject: [
    { label: "英文", count: 98 },
    { label: "數學", count: 86 },
    { label: "中文", count: 54 },
    { label: "理科", count: 42 },
    { label: "其他", count: 32 },
   ],
   byClassKind: [
    { label: "專科班", count: 240 },
    { label: "私人課程", count: 72 },
   ],
   statusBuckets: {
    registration: [
     { label: "已註冊", count: 280 },
     { label: "非註冊", count: 48 },
    ],
    enrollment: [
     { label: "在讀", count: 312 },
     { label: "非在讀", count: 16 },
    ],
    activity: [
     { label: "活躍生", count: 268 },
     { label: "非活躍生", count: 60 },
    ],
    academicStage: [
     { label: "中學階段", count: 300 },
     { label: "已畢業", count: 28 },
    ],
   },
   classFill: [
    { classId: "c1", label: "英文 F3A", enrolled: 9, capacity: 10, fillPct: 90 },
    { classId: "c2", label: "數學 F4B", enrolled: 8, capacity: 8, fillPct: 100 },
    { classId: "c3", label: "中文 F2C", enrolled: 7, capacity: 10, fillPct: 70 },
    { classId: "c4", label: "英文 F5 一對一", enrolled: 1, capacity: 1, fillPct: 100 },
   ],
   byTeacher: [
    { teacherId: "t1", name: "陳老師", enrollmentCount: 42 },
    { teacherId: "t2", name: "李老師", enrollmentCount: 38 },
    { teacherId: "t3", name: "王老師", enrollmentCount: 31 },
    { teacherId: "t4", name: "黃老師", enrollmentCount: 27 },
   ],
  },
  alerts: {
   unpaid: {
    ok: [
     { id: "p1", studentName: "陳小明", paymentDate: "2026-07-01", amount: 2750, status: "待繳費" },
     { id: "p2", studentName: "李美華", paymentDate: "2026-07-05", amount: 1650, status: "待收款" },
     { id: "p3", studentName: "王大文", paymentDate: "2026-07-10", amount: 825, status: "待繳費" },
    ],
   },
   lessonGaps: {
    ok: [
     {
      enrollmentId: "e1",
      classId: "c1",
      classLabel: "英文 F3A",
      enrollDate: "2026-04-01",
      enrollmentPeriod: null,
      paidLessons: 8,
      boundLessons: 6,
      pendingLessons: 0,
      leaveAwaitingMakeupCount: 0,
      gap: 2,
      isAligned: false,
      pendingRows: [],
      leaveAwaitingMakeupRows: [],
      studentId: "s1",
      studentCode: "S001",
      studentName: "陳小明",
      englishName: null,
     },
    ],
   },
   nearFullClasses: {
    ok: [
     { classId: "c2", label: "數學 F4B", enrolled: 8, capacity: 8, fillPct: 100 },
     { classId: "c1", label: "英文 F3A", enrolled: 9, capacity: 10, fillPct: 90 },
    ],
   },
   recentWithdrawals: {
    ok: [
     {
      id: "w1",
      studentName: "林子豪",
      classLabel: "英文 F3A",
      effectiveDate: "2026-07-18",
     },
     {
      id: "w2",
      studentName: "黃詩涵",
      classLabel: "數學 F4B",
      effectiveDate: "2026-07-20",
     },
    ],
   },
  },
  partialLoadFailed: false,
 }
}
