#!/usr/bin/env python3
"""Generate SQL to import v3.6 timetable classes missing from production.

Compares docs/year/2627/timetable/versions/v3.6/2627_timetable_class_codes_v3.6.csv
against live `classes.course_code_full` for academic year 2627.

Usage (repo root):
  python3 scripts/import_2627_missing_classes.py
    → import-output/2627_missing_classes_insert.sql
    → import-output/2627_missing_classes_report.json
"""

from __future__ import annotations

import csv
import json
import re
import uuid
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "docs/year/2627/timetable/versions/v3.6/2627_timetable_class_codes_v3.6.csv"
OUT_SQL = ROOT / "import-output/2627_missing_classes_insert.sql"
OUT_REPORT = ROOT / "import-output/2627_missing_classes_report.json"

NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
YEAR_LABEL = "2627"
YEAR_ID = "978d2726-efdd-48db-aae7-3598c463e5d8"
START = date(2026, 9, 1)
END = date(2027, 6, 30)

TEACHERS = {
    "Katie": "1f501fa8-dc4f-4d6b-b67b-3381e420acaa",
    "Katie Lee": "1f501fa8-dc4f-4d6b-b67b-3381e420acaa",
    "Christine Fan": "f1ee1000-0000-4000-8000-000000001012",
    "Billy Shek": "f1ee1000-0000-4000-8000-000000001016",
}

ROOMS = {
    "17E": "03cc2c78-d80c-4920-ac76-3fed12d1c859",
    "山案座": "9b8d95ae-e2b7-4062-8b10-f608d41a0298",
}

COURSE_BY_BASE = {
    "CHIS1001": "cf8d438e-1656-44c7-9e99-1e8c3c5fedbe",
    "CHIS2001": "977771ca-607e-4770-aed9-1956d4f3f76c",
    "CHIS3001": "1f8c58bb-7da8-4733-adce-7d54d8f68ba5",
    "CHIS4001": "a34c5169-e1e8-4ac6-804e-20e79ea34b5d",
    "CHIS5001": "69d78034-8f74-4704-847b-fba090f532ba",
    "CHIS6001": "ad84f651-aa0e-4bdd-8437-a4f4f99d85d2",
}

GRADE_BY_BASE = {
    "CHIS1001": ["中一"],
    "CHIS2001": ["中二"],
    "CHIS3001": ["中三"],
    "CHIS4001": ["中四"],
    "CHIS5001": ["中五"],
    "CHIS6001": ["中六"],
}

WD_MAP = {
    "星期一": 1,
    "星期二": 2,
    "星期三": 3,
    "星期四": 4,
    "星期五": 5,
    "星期六": 6,
    "星期日": 0,
}

# 2627 專科校舍假（附件甲 21 日）— 與 migration 20260821033000 一致
CLOSURE_DATES = {
    date(2026, 9, 18),
    date(2026, 10, 1),
    date(2026, 10, 19),
    date(2026, 10, 29),
    date(2026, 11, 26),
    date(2026, 12, 17),
    date(2026, 12, 25),
    date(2026, 12, 26),
    date(2027, 1, 1),
    date(2027, 1, 18),
    date(2027, 1, 29),
    date(2027, 2, 12),
    date(2027, 2, 13),
    date(2027, 2, 14),
    date(2027, 2, 15),
    date(2027, 2, 16),
    date(2027, 2, 17),
    date(2027, 2, 18),
    date(2027, 3, 29),
    date(2027, 4, 3),
    date(2027, 4, 5),
    date(2027, 4, 6),
    date(2027, 5, 1),
    date(2027, 5, 24),
    date(2027, 6, 22),
}

# Hard-coded missing rows (2026-08-28 prod diff)
MISSING_CODES = [
    "2627-CHIS5001-C",
    "2627-CHIS6001-C",
    "2627-CHIS4001-C",
    "2627-CHIS3001-F",
    "2627-CHIS2001-G",
    "2627-CHIS2001-F",
    "2627-CHIS1001-F",
]


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def parse_time_slot(raw: str) -> tuple[str, str, str]:
    t = raw.replace("-", "–").strip()
    m = re.match(r"^(\d{2}:\d{2})–(\d{2}:\d{2})$", t)
    if not m:
        raise ValueError(f"bad time slot: {raw}")
    return t, m.group(1), m.group(2)


def course_base_from_full(code: str) -> str:
    # 2627-CHIS5001-C → CHIS5001
    m = re.match(r"^2627-([A-Z0-9]+)-[A-Z0-9]$", code)
    if not m:
        raise ValueError(code)
    return m.group(1)


def section_from_full(code: str) -> str:
    return code.rsplit("-", 1)[-1]


def class_id_for(code: str) -> str:
    return str(uuid.uuid5(NS, f"2627-missing-class:{code}"))


def schedule_dates(weekday: int) -> list[date]:
    out: list[date] = []
    d = START
    while d <= END:
        if d.weekday() == weekday and d not in CLOSURE_DATES:
            out.append(d)
        d += timedelta(days=1)
    return out


def load_csv_rows() -> dict[str, dict[str, str]]:
    with CSV_PATH.open(encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))
    code_key = [k for k in rows[0] if "course_code" in k][0]
    return {r[code_key].strip(): r for r in rows}


def main() -> None:
    by_code = load_csv_rows()
    lines: list[str] = [
        "-- 2627 v3.6 missing classes + schedules",
        "-- Generated by scripts/import_2627_missing_classes.py",
        "begin;",
    ]
    report: dict = {"classes": [], "schedule_count": 0}

    for code in MISSING_CODES:
        row = by_code[code]
        base = course_base_from_full(code)
        section = section_from_full(code)
        teacher = TEACHERS[row["任教老師"].strip()]
        room = ROOMS[row["課室"].strip()]
        course_id = COURSE_BY_BASE[base]
        grade = GRADE_BY_BASE[base]
        time_slot, start_t, end_t = parse_time_slot(row["時段"])
        dow = row["星期"].strip()
        wd = WD_MAP[dow]
        cid = class_id_for(code)

        lines += [
            "",
            f"-- {code} {row['班別']}",
            "insert into public.classes (",
            "  id, subject, course_id, academic_year_id, section_code, course_code_full,",
            "  grade, day_of_week, time_slot, lesson_slots_per_session,",
            "  teacher_id, classroom_id, start_date, end_date, status",
            ") values (",
            f"  {sql_str(cid)}::uuid, {sql_str('中國語文')}, {sql_str(course_id)}::uuid,",
            f"  {sql_str(YEAR_ID)}::uuid, {sql_str(section)}, {sql_str(code)},",
            f"  array[{sql_str(grade[0])}]::text[], {sql_str(dow)}, {sql_str(time_slot)}, 1,",
            f"  {sql_str(teacher)}::uuid, {sql_str(room)}::uuid,",
            f"  date '2026-09-01', date '2027-06-30', '進行中'",
            ") on conflict (id) do nothing;",
        ]

        dates = schedule_dates(wd)
        session = 1
        for d in dates:
            sid = str(uuid.uuid5(NS, f"2627-missing-sched:{code}:{d.isoformat()}"))
            lines.append(
                "insert into public.schedules ("
                "id, class_id, teacher_id, classroom_id, scheduled_date, start_time, end_time, status, session_number"
                ") values ("
                f"{sql_str(sid)}::uuid, {sql_str(cid)}::uuid, {sql_str(teacher)}::uuid, {sql_str(room)}::uuid, "
                f"date {sql_str(d.isoformat())}, {sql_str(start_t)}, {sql_str(end_t)}, '預定', {session}"
                ") on conflict (id) do nothing;"
            )
            session += 1

        report["classes"].append({"code": code, "schedules": len(dates)})
        report["schedule_count"] += len(dates)

    lines.append("commit;")

    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_REPORT.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL} ({len(MISSING_CODES)} classes, {report['schedule_count']} schedules)")


if __name__ == "__main__":
    main()
